# Generated by Django 3.2 on 2021-04-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathonsite', '0005_auto_20210425_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='problem_upload',
        ),
    ]
