# Generated by Django 3.0.7 on 2021-04-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
